version: '3.8'

services:
  # Main API Gateway service
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=${DATABASE_URL}
      - AI_AGENT_URL=http://ai-agent:8080
      - SESSION_SECRET=${SESSION_SECRET:-default-secret-key}
    depends_on:
      - ai-agent
      - db
    networks:
      - ai-sql-network
    restart: unless-stopped

  # AI Agent service
  ai-agent:
    build:
      context: ./ai_agent
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - ai-sql-network
    restart: unless-stopped

  # PostgreSQL database
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ai-sql-network
    restart: unless-stopped

networks:
  ai-sql-network:
    driver: bridge

volumes:
  postgres-data: